rule_events.go

Add new webhook events `discussion` and `discussion_comment`.
- discussion: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#discussion
- discussion_comment: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#discussion_comment

add rules discussion and discussion_comment

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.pre-commit-hook.yaml
Dockerfile
docs/usage.md

Is making actionlint available as a Docker image a possibility?
This PR illustrates what the implementation could look like. An account on a Docker image repository is required.

Add Docker image for pre-commit

---

docs/usage.md

The original url
https://hub.docker.com/repository/docker/rhysd/actionlint
required user to log in, while the modified one
https://hub.docker.com/r/rhysd/actionlint
does not.
This change makes using docker images more accessible for users without docker account.

Modify dockerhub url in usage.md

---

docs/checks.md
testdata/examples/shell_name_validation.out
testdata/examples/shell_name_validation.yaml

The [shell name validation check](https://github.com/rhysd/actionlint/blob/main/docs/checks.md#check-shell-names) documentation has the following example:
```yaml
linux:
runs-on: ubuntu-latest
steps:
- run: echo 'hello'
shell: dash
- run: echo 'hello'
shell: powershell
- run: echo 'hello'
shell: powershell
```
As done in this PR, the `OK: 'powershell' is only available on Windows` section should be moved to the Windows section.

Fix shell name validation example and test

---

expr_sema.go
testdata/examples/contexts_and_buitin_funcs.yaml

Not sure when it showed up on github.com, but `runner.name` has been available since at least GHE 2.22, the first GHE release with Actions.
https://docs.github.com/en/enterprise-server@2.22/actions/learn-github-actions/contexts#runner-context
I wasn't sure where to put a test, so hope my choice is okay.
Thanks!

`name` is a valid property of `runner`

---

docs/install.md

Hi guys,
I created an `asdf` plugin for your linter.
You'll find below the current PR made againt the asdf plugin repository to be able to install actionlint just by name reference (without having to pass the plugin git repo url): 
https://github.com/asdf-vm/asdf-plugins/pull/530

add actionlint asdf plugin reference in the install.md documentation

---

popular_actions.go

Closes #139
Verified locally that running `actionlint` while having the new actions/setup-go@v3 input no longer returns the error.

Regenerate popular actions data

---

parse.go

I want to lint below invalid reusable workflow
```
on:
workflow_call:
inputs:
test_input:
description: test
type: string
required: true  # set this input is required
default: a      # but default value is provided
```
When we call this workflow without `test_input`, it results like this. I made this mistake sometimes.
```
The workflow is not valid. Input test_input is required, but not provided while calling.
```

Add lint workflow_call input conflict with required and default

---

command.go
linter.go

add support for overwriting file names when using stdin.
When I tried developing a VSCode extension for actionlint, I felt it would be helpful if we had this option.
FYI: https://github.com/fnando/vscode-linter/blob/main/docs/creating-linters.md
For example, eslint has this kind of option. https://eslint.org/docs/user-guide/command-line-interface#--stdin-filename
With --stdin-filename 
```
shun@Mac-mini actionlint % echo "foo"|  ./actionlint --stdin-filename "test.yml" -
test.yml:1:1: workflow is scalar node but mapping node is expected [syntax-check]
|
1 | foo
| ^~~
test.yml:1:1: "jobs" section is missing in workflow [syntax-check]
|
1 | foo
| ^~~
```
Without --stdin-filename 
```
shun@Mac-mini actionlint % echo "foo"|  ./actionlint -
<stdin>:1:1: workflow is scalar node but mapping node …
```

add stdin-filename support

---

.github/workflows/release.yaml
Dockerfile

This adds support for Mac M1 (and other arm processors)

Add multi platform build for Docker image

---

expr_sema.go

`github` not just exposes `actor`, but also `triggering_actor`.

fix: fix validation of github.triggering_actor

---

parse.go

Add `run-name` to expected keys for `workflow` section

---

CONTRIBUTING.md
playground/index.html
playground/style.css

Put this together quickly after pasting a workflow file into the playground and being briefly confused that the lint results disappeared (they were at the top of the page).
This updates the styling on the content of the [playground](https://rhysd.github.io/actionlint/)'s right pane to be sticky so that it stays in view when at the bottom of a long workflow file:
[sticky right pane preview](https://user-images.githubusercontent.com/3742559/205741762-497e264e-817a-4936-9e4f-f9ed03c27224.webm)
Note that this is arguably worse UX if there's many lint results (and a long workflow file) as you now have to scroll past the entire workflow file to get to the lint results near the bottom:
[many lint results preview](https://user-images.githubusercontent.com/3742559/205742868-5055e2c1-ed3f-446d-ba72- …

Make the playground's right pane content sticky

---

docs/install.md

[install.md](https://github.com/rhysd/actionlint/blob/main/docs/install.md) lacks information about how to install actionlint using [Nix](https://nixos.wiki/).
Some users will find it useful if there is a link.

docs: add installation by nix

---

.github/workflows/release.yaml

- Continuation of #267
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @rhysd. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.
You can test out the action inputs in this …

Add Winget Releaser workflow

---

.github/workflows/winget.yaml

The `version` parameter is optional and derived from the `release-tag`, which usually cuts the `v` prefix from it. Otherwise, it would lead to an incorrect `PackageVersion` such as https://github.com/microsoft/winget-pkgs/pull/102052.

Remove `version` parameter in Winget workflow

---

docs/usage.md

It looks like support for `-color` option with Problem Matchers was added in 62510ae8f7d17fd5313d76a13436f1de255fe2d8

Remove outdated Problem Matchers `-color` note

---

rule_runner_label.go

source https://github.blog/changelog/2023-04-24-github-actions-faster-macos-runners-are-now-available-in-open-public-beta/
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
fixes #296

add macos-13, macos-13-xl, macos-12-xl  rule_runner_label.go

---

docs/usage.md

Adjust URLs since super-linter repository moved
from https://github.com/github/super-linter
to https://github.com/super-linter/super-linter

usage.md: Adjust outdated links

---

linter.go
linter_test.go

Hi, I have just started using `actionlint` and it is a great tool indeed.
I was just surprised that shell checks were disabled silently on my machine because the command was not found.
This pull request aims at solving this small unsafety. The consequence is that some invocations may fail and the user shall disable (or fix) shellcheck/pyflakes explicitly. Default values remain unchanged.
I added tests to check the new behaviour.

Stronger external checks

---

.pre-commit-hooks.yaml

Refer <https://github.com/scop/pre-commit-shfmt/blob/main/.pre-commit-hooks.yaml>

change language of .pre-commit-hooks.yaml to golang

---

.github/workflows/release.yaml

Unrelated to the issue in #293, but Winget Releaser now supports non-Windows runners.

Change Winget job runner to `ubuntu-latest`

---

linter.go
process.go
process_test.go

Rename _newConcurrentProcess_ in _NewConcurrentProcess_ to be accessible from the Golang library, otherwise It's not possible to call rules such as _NewRuleShellcheck_
Thanks for this incredible work :)

Rename newConcurrentProcess in NewConcurrentProcess

---

linter.go
process.go
process_test.go
rule.go
rule_action.go
rule_credentials.go
rule_deprecated_commands.go
rule_env_var.go
rule_events.go
rule_expression.go
rule_glob.go
rule_id.go
rule_if_cond.go
rule_job_needs.go
rule_matrix.go
rule_permissions.go
rule_pyflakes.go
rule_runner_label.go
rule_shell_name.go
rule_shellcheck.go
rule_workflow_call.go

I've added a constructor for _RuleBase_ and changed _error_ and _errorf_ from private to public, otherwise It's not possible to create new rules. I hope that this is the best option, if not, how should we create new rules when using _actionlint_ as a library ? 
I also changed _wait_ from private to public in _process.go_.

Changes to make actionlint usable when using it as a library

---

rule.go
rule_action.go
rule_expression.go
rule_pyflakes.go
rule_shellcheck.go
rule_workflow_call.go

Make debug public

---

all_webhooks.go

The activity type `starred` is wrong.
The correct activity type is `started`.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#watch
GitHub's official document was wrong, so I fixed it.
- https://github.com/github/docs/pull/27127
- https://github.com/github/docs/issues/27129

fix: fix activity types of the event `watch`

---

ast.go
reusable_workflow.go
rule_runner_label.go

Make `ContainsExpression(s string) `public as `(s *String) ContainsExpression() ` is already public. This can be usefull when using actionlint as a library.

make ContainsExpression(s string) public

---

.gitignore
rule_runner_label.go
rule_runner_label_test.go

Add glob support for self hosted runner known labels configuration

---

docs/usage.md

When using `rev: main`, pre-commit throws the following warning:
```log
pre-commit run --all-files               
[WARNING] The 'rev' field of repo 'https://github.com/rhysd/actionlint' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
```
From https://pre-commit.com/#using-the-latest-version-for-a-repository:
>Using the latest version for a repository ¶
pre-commit configuration aims to give a repeatable and fast experience and therefore intentionally doesn't provide facilities for "unpinned latest version" for hook repositories.
>
>Instead, pre-commit provides tools …

Set explicit version in precommit snippet

---

scripts/generate-popular-actions/main.go

For your consideration, this adds several probably commonly used actions to the list of known actions.
In particular, it was common to use `service_account_key` with google-github-actions/setup-gcloud@v0 to do simple token-via-a-secret authentication. However google-github-actions/setup-gcloud@v1 ignores this option and wants that style of authentication to be expressed in a different way. So for people updating workflows that use setup-gcloud, it's very useful for actionlint to detect the error that will result from just applying `s/@v0/@v1/`.
We use setup-gcloud and auth ourselves; the four I've added here are the most fundamental-looking of the google-github-actions organisation's pinned actions repositories.
I've taken the liberty of also adding pypa/gh-action-pypi-publish as it is …

Add several google-github-actions etc to generate-popular-actions list

---

docs/usage.md

Howdy!
I have recently published a package to integrate this amazing linter into an Emacs diagnostic provider and @ROCKTAKEY has done the same for the builtin mechanism.
To increase the visibility of these packages and help your users integrate actionlint into their workflows easier, I updated the usage docs.
Please let me know if I should change anything, and thank you for contributing such an awesome piece of software to the community, it's been a life-saver 😸

Add usage instructions for Emacs

---

docs/install.md

In addition to the AUR, [`actionlint`](https://archlinux.org/packages/extra/x86_64/actionlint/) is also available in the Arch Linux official repository.

Add the Arch Linux official repository in the installation documentation

---

.pre-commit-hooks.yaml
scripts/bump-version.bash

Alternative container engines such as podman don't default to Docker Hub and require specifying the fully qualified container url.

pre-commit: include fully qualified container name

---

docs/usage.md
man/actionlint.1.ronn

`actions/checkout@v3` produces a warning about deprecated Node.js version ([see also](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)).

Update `checkout` action version in documentation

---

.github/workflows/generate.yaml

As it's unnecessary (as the needed PR will be opened by workflow runs in this, the original "upstream" repository) and only causes noise in forks. See for example [this run](https://github.com/muzimuzhi/actionlint/actions/runs/11305433070/job/31444920812#annotation:7:100) in my fork.

Skip PR creation in the generate workflow in forks

---

.gitignore
expr_ast.go
expr_insecure.go
expr_insecure_test.go
expr_parser.go

Currently there are cases when `actionlint` falsely assumes expression to be unsafe when used inside scripts and warns about possible script injection.
For instance, following step description:
```yaml
- name: Determine if release branch
run: |
echo "is_release_branch=${{ contains(github.head_ref, 'release') }}" >> $GITHUB_OUTPUT
```
would lead to warning:
```
.github/workflows/test.yaml:17:51: "github.head_ref" is potentially untrusted. avoid using it directly in inline scripts. instead, pass it through an environment variable. see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions for more details [expression]
```
The only place which I suppose relevant to the issue is this: https://docs.github.com/en/actions/security-for-github-actions/security-guid …

Fix false-positive script injection warnings when using builtin functions with stable outputs

---

rule_action.go

SSIA
gcr.io and pkg.dev is docker registry domain for GCP
* gcr.io: 
https://cloud.google.com/container-registry/docs/overview
* pkg.dev
https://cloud.google.com/artifact-registry/docs

add gcr.io and pkg.dev to valid docker regstry domain

---

docs/checks.md

Following up this commit.
https://github.com/rhysd/actionlint/commit/c71a576bdf418ffa9cc06b8f7d0cb7a500fa4846

docs: add SC2043 to disabled shellcheck rules

---

config_test.go
error_test.go
expr_parser_test.go
expr_sema_test.go
expr_type_test.go
linter_test.go
reusable_workflow_test.go
rule_deprecated_commands_test.go
rule_workflow_call_test.go
scripts/check-checks/main_test.go
scripts/generate-availability/main_test.go
scripts/generate-popular-actions/main_test.go
scripts/generate-webhook-events/main_test.go

This PR refactors tests. These code blocks
```go
if !cmp.Equal(want, got) {
t.Fatal(cmp.Diff(want, got))
}
```
```go
if !bytes.Equal(want, got) {
t.Fatal(cmp.Diff(want, got))
}
```
```go
if want != got {
t.Fatal(cmp.Diff(want, got))
}
```
changed to the following:
```go
if diff := cmp.Diff(want, got); diff != "" {
t.Fatal(diff)
}
```

simplify tests with cmp.Diff

---

docs/checks.md
rule_action.go
testdata/examples/.github/actions/my-invalid-action/action.yml
testdata/examples/action_metadata_syntax_validation.out

The official GitHub documentation lists it as a supported color: https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#brandingcolor 
Fixes: #484

Support branding.color "black"

---

go.mod
go.sum
process.go
process_test.go

closes #480 
If an external command (shellcheck, pyflakes) is not found, try to parse it as a exe+args using [go-shellwords](https://github.com/mattn/go-shellwords), which can allow executing without having the binary installed i.e., `go run github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0`, `pipx run pyflakes`.

support commands specified as exe/args

---

expr_sema.go

See https://www.google.com/search?q=github+%22repository_visibility%22
As a workaround, one can add this to your `actionlint.yml` file:
```yaml
paths:
.github/workflows/**/*:
ignore:
- 'repository_visibility'
```

fix: Add undocumented github.repository_visibility option

---

.github/workflows/ci.yaml

Projects are speeding up GitHub Actions by running them on an ARM processor. https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Run unit test GitHub Action on an ARM processor

---

action_metadata.go

This PR adds support for the `deprecationMessage` input parameter under the `inputs` section for reusable workflows triggered via `workflow_call`.
GitHub supports [deprecationMessage](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#inputsinput\_iddeprecationmessage) field in the metadata syntax for reusable workflows. This field allows maintainers to mark inputs as deprecated and provide contextual messaging for downstream consumers.
However, `actionlint` currently treats `deprecationMessage` as an unknown key and fails with the following error:
```
unexpected key "deprecationMessage" for "inputs at workflow_call event" section. expected one of "default", "description", "required", "type" [syntax-check]
```
This causes valid …

chore: add support for additional github action input parameters

---

expr_sema.go

`job.check_run_id` property has type `number`, not `string`.
- GitHub Docs https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#job-context
- example run
https://github.com/dhimmel/dump-actions-context/actions/runs/18170960955/job/51725241954#step:12:354
I asked why it has `number` type [here](https://github.com/orgs/community/discussions/8945#discussioncomment-14481081), but got no response from GitHub staff.

Fix type of `job.check_run_id` property
